openapi: "3.0.2"
info:
  version: 1.0.0
  title: Kalah Game Board
  license:
    name: GNU
servers:
  - url: http://localhost:8080
paths:

  /games/{gameId}/pits/{pitId}:
    put:
      summary: Executes a move by a player
      operationId: executeMove
      parameters:
        - name: gameId
          in: path
          required: true
          description: ID of the game
          schema:
            type: string
        - name: pitId
          in: path
          required: true
          description: Pit number to make the move with
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Current Status of the game after the move
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameStatus"
        400:
          description: Errors made by players
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
        404:
          description: Game not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"


  /games:
    post:
      summary: Create a new Game
      operationId: createGame
      responses:
        '201':
          description: Created Game Details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateGameResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

components:
  schemas:

    GameStatus:
      type: object
      required:
        - amount
        - type
      properties:
        id:
          type: string
        link:
          type: string
        state:
          type: string
        status:
          type: object
          additionalProperties:
            type: string

    CreateGameResponse:
      type: object
      properties:
        id:
          type: string
        link:
          type: string

    ErrorObject:
      type: object
      required:
        - code
        - message
      properties:
        statusCode:
          type: integer
          format: int32
        message:
          type: string
